language: node_js

node_js:
  - "8"

before_install:
  - cd app

install:
  - npm install

os:
  - linux
  - osx

env:
  - TARGET_ARCH=x64

script:
  - npm run dist

branches:
  only:
    - master

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN